### ISSUE TITLE
rails 5 error "not opened for reading"

### ISSUE THREAD

**Issue by oshanz** [cmertz/logstash_rails#6]
ruby 2.3.0
rails 5.0.0.1

log :

Started GET "/" for 127.0.0.1 at 2016-09-04 10:07:13 +0530

IOError (not opened for reading):

activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:130:in `each'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:130:in`to_a'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:130:in `as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in`block in as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in `map'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in`as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in `block in as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in`map'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:142:in `as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:130:in`as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:161:in`each'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:161:in `map'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:161:in`as_json'
activesupport (5.0.0.1) lib/active_support/json/encoding.rb:33:in `encode'
activesupport (5.0.0.1) lib/active_support/json/encoding.rb:20:in`encode'
activesupport (5.0.0.1) lib/active_support/core_ext/object/json.rb:37:in `to_json'
logstash-event (1.2.02) lib/logstash/event.rb:169:in`to_json'
logstash_rails (0.3.2) lib/logstash_rails/formatter_base.rb:14:in `perform'
logstash_rails (0.3.2) lib/logstash_rails/transport_base.rb:41:in`event_handler'
activesupport (5.0.0.1) lib/active_support/notifications/fanout.rb:127:in `call'
activesupport (5.0.0.1) lib/active_support/notifications/fanout.rb:127:in`finish'
activesupport (5.0.0.1) lib/active_support/notifications/fanout.rb:46:in `block in finish'
activesupport (5.0.0.1) lib/active_support/notifications/fanout.rb:46:in`each'
activesupport (5.0.0.1) lib/active_support/notifications/fanout.rb:46:in `finish'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:42:in`finish_with_state'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:27:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in`instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:28:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in`process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in`process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in`dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in`dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in`block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in`serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in`call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in`call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.1) lib/active_record/migration.rb:552:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in`**run_callbacks**'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in`run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in`call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in`block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in`call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in`block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in`tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in`call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in`call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in`call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in`handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in`block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (6.6ms)
  Rendering /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.6ms)
  Rendering /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (13.6ms)
  Rendered /home/trisquel/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (53.7ms)

**Comment by cmertz** [comment]
Thanks for the bug report @oshanz. 

I should have mentioned that in the README earlier but i do not use nor maintain this gem any more.

Sorry for the inconvenience.
